node {
  stage('do something with git') {  
    sshagent (credentials: ['git-sshkey']) {
      // get the last commit id from a repository you own
      sh 'git ls-remote -h --refs git@github.com:Eduardo1911/jenkins-course.git master |awk "{print \$1}"'
    }
  }
}
